#%RAML 1.0 DataType
(package): HAL

description: >
  RAML representation of a HAL "link relation".

type: string
pattern: "^[A-Za-z](?:[A-Za-z0-9_]+-)*[A-Za-z0-9]:(?:[A-Za-z0-9]+[_.-])*[A-Za-z0-9]$"
minLength: 1
maxLength: 32

