########################################
# System-wide Types
########################################

UUID: !include ../UUID.raml


########################################
# Storage Facility Types
########################################

CompanyRecord: !include CompanyRecord.raml
CompanyStatusRecord: !include CompanyStatusRecord.raml
StorageFacilityRecord: !include StorageFacilityRecord.raml
StorageFacilityStatusRecord: !include StorageFacilityStatusRecord.raml
