#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $STORAGE_FACILITY_USER
		WITH PASSWORD '$STORAGE_FACILITY_PASSWORD';

	CREATE DATABASE $STORAGE_FACILITY_DB;
	GRANT ALL PRIVILEGES ON DATABASE $STORAGE_FACILITY_DB
		TO $STORAGE_FACILITY_USER;

	CREATE USER $INVENTORY_USER
		WITH PASSWORD '$INVENTORY_PASSWORD';

	CREATE DATABASE $INVENTORY_DB;
	GRANT ALL PRIVILEGES ON DATABASE $INVENTORY_DB
		TO $INVENTORY_USER;

EOSQL

