#!/usr/bin/env sh
# @(#) Driver script for reading all messages in a specific topic
#

KAFKA_SERVER="${KAFKA_SERVER:-localhost:9092}"

test -z "${1:-}" && {
	echo "usage: $0 <topic name>" > /dev/stderr
	exit 1
}

kafka-topics.sh --bootstrap-server $KAFKA_SERVER \
	--delete \
	--topic "$1"

