#%RAML 1.0 DataType
(package): StorageFacility
displayName: StorageFacilitiesExpansion

description: >
  StorageFacilitiesExpansion defines the discrete values
  representing the options available to expand *embedded*
  resources within a **StorageFacilities** resource.

type: string
enum:
  - all
  - none
  - company
