#%RAML 1.0 DataType
(package): StorageFacility
displayName: StorageFacilityStatus

description: >
  StorageFacilityStatus defines the discrete values representing the
  status a **StorageFacility** can have.

type: string
enum:
  - Active
  - Closed
  - UnderConstruction

