#%RAML 1.0 DataType
(package): StorageFacility
displayName: StorageFacilityExpansion

description: >
  StorageFacilityExpansion defines the discrete values
  representing the options available to expand *embedded*
  resources within a **StorageFacility** resource.

type: string
enum:
  - all
  - none
  - company
