########################################
# Type Aliases
########################################

UUID:
  (scala-type): "java.util.UUID"


########################################
# System-wide Types
########################################

Dimension: !include ../Dimension.raml
ShutdownMessage: !include ../ShutdownMessage.raml
SupportedHttpMethods: !include ../SupportedHttpMethods.raml
URL: !include ../URL.raml
URN: !include ../URN.raml
VersionOnly: !include ../VersionOnly.raml
Version: !include ../Version.raml
WebLink: !include ../WebLink.raml


########################################
# Hypertext Application Language Types
########################################

Embedded: !include ../hal/Embedded.raml
ResourceObject: !include ../hal/ResourceObject.raml
LinkObject: !include ../hal/LinkObject.raml
Links: !include ../hal/Links.raml
LinkRelation: !include ../hal/LinkRelation.raml


########################################
# Error Types
########################################

ProblemDetails: !include ../error/ProblemDetails.raml
BadRequestDetails: !include ../error/BadRequestDetails.raml
InvalidModelStateDetails: !include ../error/InvalidModelStateDetails.raml
LogicErrorDetails: !include ../error/LogicErrorDetails.raml
MinimalProblemDetails: !include ../error/MinimalProblemDetails.raml
ObjectNotFoundDetails: !include ../error/ObjectNotFoundDetails.raml
ServiceImplementationDetails: !include ../error/ServiceImplementationDetails.raml
ServiceUnavailableDetails: !include ../error/ServiceUnavailableDetails.raml
StaleObjectDetails: !include ../error/StaleObjectDetails.raml


########################################
# Event Types
########################################

CompanyActivated: !include ../company/event/CompanyActivated.raml
CompanyCreated: !include ../company/event/CompanyCreated.raml
CompanyDeleted: !include ../company/event/CompanyDeleted.raml
CompanyEvent: !include ../company/event/CompanyEvent.raml
CompanyInactivated: !include ../company/event/CompanyInactivated.raml
CompanyProfileChanged: !include ../company/event/CompanyProfileChanged.raml
CompanySlugChanged: !include ../company/event/CompanySlugChanged.raml
CompanyStatusChanged: !include ../company/event/CompanyStatusChanged.raml
CompanySuspended: !include ../company/event/CompanySuspended.raml
DistributedEvent: !include ../event/DistributedEvent.raml
DomainEvent: !include ../event/DomainEvent.raml
EventOrigin: !include ../event/EventOrigin.raml
Region: !include ../event/Region.raml
ServiceEvent: !include ../event/ServiceEvent.raml
StorageFacilityActivated: !include event/StorageFacilityActivated.raml
StorageFacilityClosed: !include event/StorageFacilityClosed.raml
StorageFacilityEvent: !include event/StorageFacilityEvent.raml
StorageFacilityCreated: !include event/StorageFacilityCreated.raml
StorageFacilityDeleted: !include event/StorageFacilityDeleted.raml
StorageFacilityProfileChanged: !include event/StorageFacilityProfileChanged.raml
StorageFacilityStatusChanged: !include event/StorageFacilityStatusChanged.raml


########################################
# Company Types
########################################

CompanySlug: !include ../company/CompanySlug.raml
CompanyStatus: !include ../company/CompanyStatus.raml


########################################
# Storage Facility Types
########################################

NewStorageFacility: !include ./NewStorageFacility.raml
StorageFacilities: !include ./StorageFacilities.raml
StorageFacility: !include ./StorageFacility.raml
StorageFacilityCompanyView: !include ./StorageFacilityCompanyView.raml
StorageFacilitiesExpansion: !include ./StorageFacilitiesExpansion.raml
StorageFacilityExpansion: !include ./StorageFacilityExpansion.raml
StorageFacilityStatus: !include ./StorageFacilityStatus.raml

