#%RAML 1.0 DataType
(package): StorageFacilityEvent
type: StorageFacilityStatusChanged
displayName: StorageFacilityClosed
discriminatorValue: "/event/domain/storage-facility/status/closed"

description: >
  The **StorageFacilityClosed** event is emitted when a
  **StorageFacility** has its **StorageFacilityStatus**
  altered to be "Closed".

