#%RAML 1.0 DataType
(package): StorageFacilityEvent
type: StorageFacilityEvent
displayName: StorageFacilityDeleted
discriminatorValue: "/event/domain/storage-facility/deleted"

description: >
  The **StorageFacilityDeleted** **StorageFacilityEvent** is
  emitted whenever a **StorageFacility** has been
  *permanently* removed from the system.

