#%RAML 1.0 DataType
(package): Error
type: ProblemDetails
displayName: MinimalProblemDetails
discriminatorValue: "/problem"

description: >
  The **MinimalProblemDetails** type is a **ProblemDetails** which
  has no additional (context-specific) problem details extensions.
