{
 "title": "HikariCP",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "microservice", "query": { "query": "label_values(service)" } },
   { "name": "pool", "query": { "query": "label_values(jdbc_pool_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Connections Borrowed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(jdbc_pool_connections_borrowed_count{service=~\"$microservice\", jdbc_pool_name=~\"$pool\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Statements In Flight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(jdbc_statements_in_flight_count{service=~\"$microservice\", jdbc_pool_name=~\"$pool\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Borrow Time",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(jdbc_pool_borrow_time_seconds_bucket{service=~\"$microservice\", jdbc_pool_name=~\"$pool\",le=\"0.01\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(jdbc_pool_borrow_time_seconds_bucket{service=~\"$microservice\", jdbc_pool_name=~\"$pool\",le=\"0.25\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(jdbc_pool_borrow_time_seconds_bucket{service=~\"$microservice\", jdbc_pool_name=~\"$pool\",le=\"+Inf\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}