{
 "title": "Kafka/REST",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "microservice", "label": "Microservice", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  {
   "title": "Apdex Score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\nsum(rate(span_processing_time_seconds_bucket{service=~\"$microservice\",component=\"tapir\",le=\"0.25\"}[$__range])) by (service)\n\n+\n\nsum(rate(span_processing_time_seconds_bucket{service=~\"$microservice\",component=\"tapir\",le=\"1.0\"}[$__range])) by (service)\n)\n\n/ 2 / sum(rate(span_processing_time_seconds_count[$__range])) by (service)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REST Total Failures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_metrics_rest_failed_total{service=~\"$microservice\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REST Processing Time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "span_processing_time_seconds_bucket{service=~\"$microservice\",component=\"tapir\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REST Call Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(app_metrics_rest_called_total{service=~\"$microservice\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Karaf Published Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(app_metrics_event_publish_company_called_total{service=~\"$microservice\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(app_metrics_event_publish_storage_facility_called_total{microservice=~\"$microservice\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REST Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(app_metrics_rest_succeeded_total{service=~\"$microservice\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Karaf Consumed Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(app_metrics_event_consume_company_called_total{service=~\"$microservice\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(app_metrics_event_consume_storage_facility_called_total{service=~\"$microservice\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REST Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(app_metrics_rest_failed_total{service=~\"$microservice\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}