{
 "title": "Kamon 2.x - System metrics dashboard",
 "description": "System metrics dashboard for apps instrumented with Kamon 2.x",
 "tags": [
  "kamon",
  "prometheus",
  "system-metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values({component=\"host\"},service)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System resources overview",
   "type": "bargauge",
   "description": "System resources usage",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(host_cpu_usage_sum{instance=~\"$instance\", mode=\"combined\"}[$interval]))\n/\nsum(rate(host_cpu_usage_count{instance=~\"$instance\", mode=\"combined\"}[$interval]))",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "host_memory_used_bytes{instance=~\"$instance\"}\n/\nhost_memory_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Memory utilization"
    },
    {
     "expr": "(host_swap_memory_used_bytes{instance=~\"$instance\"}\n/\nhost_swap_memory_total_bytes{instance=~\"$instance\"}) OR on() vector(0)",
     "legendFormat": "SWAP utilization"
    }
   ]
  },
  {
   "title": "CPU %usr",
   "type": "stat",
   "description": "Tracks the current time the CPU is busy on user mode.",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(host_cpu_usage_sum{instance=~\"$instance\", mode=\"user\"}[$interval]))\n/\nsum(rate(host_cpu_usage_count{instance=~\"$instance\", mode=\"user\"}[$interval]))"
    }
   ]
  },
  {
   "title": "CPU %system",
   "type": "stat",
   "description": "Tracks the current time the CPU is busy on system mode.",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(host_cpu_usage_sum{instance=~\"$instance\", mode=\"system\"}[$interval]))\n/\nsum(rate(host_cpu_usage_count{instance=~\"$instance\", mode=\"system\"}[$interval]))"
    }
   ]
  },
  {
   "title": "CPU %wait",
   "type": "stat",
   "description": "Tracks the current time the CPU is stuck waiting for IO.\n\nIf this value is high, the disk might be the bottleneck.",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(host_cpu_usage_sum{instance=~\"$instance\", mode=\"wait\"}[$interval]))\n/\nsum(rate(host_cpu_usage_count{instance=~\"$instance\", mode=\"wait\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "bargauge",
   "description": "Traks network usage",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(host_network_data_read_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(host_network_data_write_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Retransmits",
   "type": "bargauge",
   "description": "Tracks ratio for failed network packets",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(host_network_packets_read_failed_total{instance=~\"$instance\"})\n/\nsum(host_network_packets_read_total_total{instance=~\"$instance\"})",
     "legendFormat": "read"
    },
    {
     "expr": "sum(host_network_packets_write_failed_total{instance=~\"$instance\"})\n/\nsum(host_network_packets_write_total_total{instance=~\"$instance\"})",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Top 2 Disk usage",
   "type": "stat",
   "description": "Tracks usage of space on Disk",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(2, (sum by(mount)(host_storage_mount_space_used_bytes{instance=~\"$instance\"})\n/\nsum by(mount)(host_storage_mount_space_total_bytes{instance=~\"$instance\"})))",
     "legendFormat": "{{mount}}"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "bargauge",
   "description": "Tracks the system load average in 1m / 5m / 15m.\n\nThey indicate the average number of tasks (processes) wanting to run in the last 1m / 5m / 15m.\n\nOn Linux systems, these numbers is approximated and include processes wanting to run on the CPUs, as well as processes blocked in uninterruptible I/O (usually disk I/O).\nThis gives a high-level idea of resource load (or demand).\n\nThe three numbers give some idea of how load is changing over time.\n\nExcellent post on the subject: http://www.brendangregg.com/blog/2017-08-08/linux-load-averages.html",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "host_load_average{instance=~\"$instance\", period=\"1m\"}",
     "legendFormat": "Avg. 1m"
    },
    {
     "expr": "host_load_average{instance=~\"$instance\", period=\"5m\"}",
     "legendFormat": "Avg. 5m"
    },
    {
     "expr": "host_load_average{instance=~\"$instance\", period=\"15m\"}",
     "legendFormat": "Avg. 15m"
    }
   ]
  },
  {
   "title": "Proc %usr",
   "type": "stat",
   "description": "Tracks the current time the CPU is busy by the process in user mode.",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_usage_sum{instance=~\"$instance\", mode=\"user\"}[$interval]))\n/\nsum(rate(process_cpu_usage_count{instance=~\"$instance\", mode=\"user\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Proc %system",
   "type": "stat",
   "description": "Tracks the current time the CPU is busy by the process in kernel mode.",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_usage_sum{instance=~\"$instance\", mode=\"system\"}[$interval]))\n/\nsum(rate(process_cpu_usage_count{instance=~\"$instance\", mode=\"system\"}[$interval]))"
    }
   ]
  },
  {
   "title": "CPU %steal",
   "type": "stat",
   "description": "Tracks the current time the CPU is stolen by some process outside the VM.\n\nIf this value is high, it could be caused either by the supervisor is very busy, by a noisy neighbor or by some limitation on the quota assigned by the virtualization service.",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(host_cpu_usage_sum{instance=~\"$instance\", mode=\"stolen\"}[$interval]))\n/\nsum(rate(host_cpu_usage_count{instance=~\"$instance\", mode=\"stolen\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "bargauge",
   "description": "Traks the usage of disk space",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(host_storage_device_data_read_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(host_storage_device_data_write_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "# FDs",
   "type": "stat",
   "description": "Tracks the number of file descriptors in used by the process.",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_ulimit_file_descriptors_used{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Load / Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System load average in 1m / 5m / 15m",
   "type": "graph",
   "description": "Tracks the system load average in 1m / 5m / 15m.\n\nThey indicate the average number of tasks (processes) wanting to run in the last 1m / 5m / 15m.\n\nOn Linux systems, these numbers is approximated and include processes wanting to run on the CPUs, as well as processes blocked in uninterruptible I/O (usually disk I/O).\nThis gives a high-level idea of resource load (or demand).\n\nThe three numbers give some idea of how load is changing over time.\n\nExcellent post on the subject: http://www.brendangregg.com/blog/2017-08-08/linux-load-averages.html",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "host_load_average{instance=~\"$instance\", period=\"1m\"}",
     "legendFormat": "Avg 1m"
    },
    {
     "expr": "host_load_average{instance=~\"$instance\", period=\"5m\"}",
     "legendFormat": "Avg 5m"
    },
    {
     "expr": "host_load_average{instance=~\"$instance\", period=\"15m\"}",
     "legendFormat": "Avg 15m"
    }
   ]
  },
  {
   "title": "VM Hiccups (or idle jitters) in nanoseconds (p90)",
   "type": "heatmap",
   "description": "Tracks the hiccups detected in the VM (also known as idle jitters) measured in nanoseconds. The 90ht percentile is presented.\n\nFor more info: https://www.azul.com/jhiccup/",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(process_hiccups_seconds_bucket{instance=~\"$instance\"}[$interval])) by (le, instance))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "VM CPU usage",
   "type": "graph",
   "description": "Tracks the usage of CPU by the VM in the different typical views.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(host_cpu_usage_sum{instance=~\"$instance\", mode=\"user\"}[$interval])\n/\nrate(host_cpu_usage_count{instance=~\"$instance\", mode=\"user\"}[$interval])",
     "legendFormat": "User mode"
    },
    {
     "expr": "rate(host_cpu_usage_sum{instance=~\"$instance\", mode=\"system\"}[$interval])\n/\nrate(host_cpu_usage_count{instance=~\"$instance\", mode=\"system\"}[$interval])",
     "legendFormat": "Kernel mode"
    },
    {
     "expr": "rate(host_cpu_usage_sum{instance=~\"$instance\", mode=\"wait\"}[$interval])\n/\nrate(host_cpu_usage_count{instance=~\"$instance\", mode=\"wait\"}[$interval])",
     "legendFormat": "IO wait"
    },
    {
     "expr": "rate(host_cpu_usage_sum{instance=~\"$instance\", mode=\"stolen\"}[$interval])\n/\nrate(host_cpu_usage_count{instance=~\"$instance\", mode=\"stolen\"}[$interval])",
     "legendFormat": "Stolen"
    }
   ]
  },
  {
   "title": "Process CPU usage",
   "type": "graph",
   "description": "Tracks the usage of CPU by the app in the different typical views.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_usage_sum{instance=~\"$instance\", mode=\"user\"}[$interval])\n/\nrate(process_cpu_usage_count{instance=~\"$instance\", mode=\"user\"}[$interval])",
     "legendFormat": "User mode"
    },
    {
     "expr": "rate(process_cpu_usage_sum{instance=~\"$instance\", mode=\"system\"}[$interval])\n/\nrate(process_cpu_usage_count{instance=~\"$instance\", mode=\"system\"}[$interval])",
     "legendFormat": "Kernel mode"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Host Memory",
   "type": "graph",
   "description": "Tracks the total memory available Vs. the amount of used memory.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "host_memory_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "host_memory_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "Swap Memory",
   "type": "graph",
   "description": "Tracks the total swap memory available Vs. the amount of used swap memory.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "host_swap_memory_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Used Swap Memory"
    },
    {
     "expr": "host_swap_memory_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Total Swap Memory"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Read / Write bandwidth",
   "type": "graph",
   "description": "Tracks incoming and outgoing data through the network interfaces.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(host_network_data_read_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(host_network_data_write_bytes_total{instance=~\"$instance\"}[$interval]) * -1",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Failed Read / Write packets",
   "type": "graph",
   "description": "Tracks incoming and outgoing failed packets on all network interfaces.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(host_network_packets_read_failed_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(host_network_packets_write_failed_total{instance=~\"$instance\"}[$interval]) * -1",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "description": "Tracks usage of disk.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(mount)(host_storage_mount_space_used_bytes{instance=~\"$instance\"})\n/\nsum by (mount)(host_storage_mount_space_total_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{mount}}"
    }
   ]
  },
  {
   "title": "Data transferred",
   "type": "graph",
   "description": "Tracks the amount of data transferred to disk device.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(host_storage_device_data_read_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(host_storage_device_data_write_bytes_total{instance=~\"$instance\"}[$interval]) * -1",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Disk I/O (ops/sec)",
   "type": "graph",
   "description": "Tracks the number of completed disk I/O operations.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(host_storage_device_ops_read_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(host_storage_device_ops_write_total{instance=~\"$instance\"}[$interval]) * -1",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "description": "Tracks the amount of memory used by the JVM heap.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{instance=~\"$instance\", region=\"heap\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=~\"$instance\", region=\"heap\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_used_bytes_sum{instance=~\"$instance\", region=\"heap\"}\n/\njvm_memory_used_bytes_count{instance=~\"$instance\", region=\"heap\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Off-Heap",
   "type": "graph",
   "description": "Tracks the amount of memory used by the JVM outside the heap.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{instance=~\"$instance\", region=\"non-heap\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=~\"$instance\", region=\"non-heap\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_used_bytes_sum{instance=~\"$instance\", region=\"non-heap\"}\n/\njvm_memory_used_bytes_count{instance=~\"$instance\", region=\"non-heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_free_bytes_sum{instance=~\"$instance\", region=\"non-heap\"}\n/\njvm_memory_free_bytes_count{instance=~\"$instance\", region=\"non-heap\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "graph",
   "description": "Tracks the distribution of GC events duration",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_seconds_sum{instance=~\"$instance\"}[$interval])\n/\nrate(jvm_gc_seconds_count{instance =~\"$instance\"}[$interval])",
     "legendFormat": "GC count: {{collector}}"
    }
   ]
  },
  {
   "title": "Executor Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number Of Threads",
   "type": "graph",
   "description": "Tracks the number of threads in use.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(executor_threads_total_count{instance=~\"$instance\"}[$interval])\n/\nrate(executor_threads_total_sum{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ name }} ({{ type }})"
    }
   ]
  },
  {
   "title": "Number Of Tasks Completed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(executor_tasks_completed_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ name }} ({{ type }})"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(executor_queue_size_bucket{instance=~\"$instance\", le=\"+Inf\"}[$interval])",
     "legendFormat": "{{ name }} ({{ type }})"
    }
   ]
  },
  {
   "title": "Maximum Number of Threads",
   "type": "graph",
   "description": "Tracks maximum number of Threads of the executors.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "executor_threads_max{instance=~\"$instance\"}",
     "legendFormat": "{{ name }} ({{ type }})"
    }
   ]
  },
  {
   "title": "Minimum Number of Threads",
   "type": "graph",
   "description": "Tracks minimum number of Threads of the executors.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "executor_threads_min{instance=~\"$instance\"}",
     "legendFormat": "{{ name }} ({{ type }})"
    }
   ]
  },
  {
   "title": "Executor parallelism",
   "type": "graph",
   "description": "Tracks executor parallelism.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "executor_parallelism{instance=~\"$instance\"}",
     "legendFormat": "{{ name }} ({{ type }})"
    }
   ]
  }
 ]
}