#%RAML 1.0 DataType
(package): CompanyEvent
type: CompanyEvent
displayName: CompanyDeleted
discriminatorValue: "/event/domain/company/deleted"

description: >
  The **CompanyCreated** **CompanyEvent** is emitted whenever
  a **Company** has been *permanently* removed from the system.

