#%RAML 1.0 DataType
(package): Shared
displayName: SupportedHttpMethods

description: |
  Allowable HTTP methods for an `href`, as found in **WebLink**.

  See
  [HTTP methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods)
  for details.

type: string
enum:
  - DELETE
  - GET
  - HEAD
  - OPTIONS
  - PATCH
  - POST
  - PUT

