#%RAML 1.0 DataType
(package): Company
displayName: CompanySlug

description: >
  A **CompanySlug** represents a unique name associated with each
  known **Company**.  See the
  [Wikipedia description](https://en.wikipedia.org/wiki/Clean_URL#Slug)
  for more information regarding the concept of slugs.

type: string
minLength: 2
maxLength: 64
# For this system, a slug can be either a word with at least
# two characters or multiple words separated by a hyphen
# (with the first allowed to be a single letter).
#
# In all cases, the first character must be alphabetic.
pattern: "^[a-z](?:[a-z0-9]+|(?:[a-z0-9]*(?:-[a-z0-9]+)+))$"

