#%RAML 1.0 DataType
(package): Company
displayName: CompanyStatus

description: >
  **CompanyStatus** defines the discrete values representing the status
  a **Company** can have.

type: string
enum:
  - Active
  - Inactive
  - Suspended

