#%RAML 1.0 DataType
(package): Inventory
displayName: VirtualInventory

description: >
  The VirtualInventory type is a **ProductInventory** which
  represents a specific type of virtual inventory.  As such,
  it occupies no physical space.

type: ProductInventory
discriminatorValue: virtual
properties:
  location?:
    description: >
      If the **VirtualInventory** is an artifact capable of
      being retrieved (such as an audio or video recording),
      the `location` specifies where it resides.

    type: URL

