#%RAML 1.0 DataType
(package): Event
displayName: Region

description: >
  **Region** defines the concept of locality of **DomainEvent**s
  produced by services based on installations.  This is important
  when multiple groups of the same service are physically
  deployed.
  
  For example, suppose there were two data centers where an
  arbitrary service was running (on in Europe and one in North
  America).  There would be two **Region**s defined.

type: string
minLength: 2
maxLength: 32
pattern: "^[a-z][a-z0-9]*(?:-[a-z0-9]+)*(?:-(?:dev|qa|prod|stage|[0-9]+))?$"
