#%RAML 1.0 DataType
(package): Event
type: DistributedEvent
displayName: ServiceEvent
discriminatorValue: "/event/service"

description: >
  A **ServiceEvent** is a category of a **DistributedEvent**
  whose concrete instances represent significant deployment
  and/or system collaborator notifications.
  
  Examples of these could be a service starting, shutting down,
  or a persistent store being unavailable.
  
  All **ServiceEvent**s **must** have a `discriminatorValue`
  "under" the one defined here.

