# @(#) Prometheus configuration for demo system
#
# The "targets" ports are those exposed by each service in their respective
# docker-compose.yml.  Since multiple services can run on a single machine,
# each are assigned unused ports (as per /etc/services).

global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - "localhost:9090"

  - job_name: "company"
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [ "company:9095" ]
        labels:
          microservice: company

  - job_name: "storage-facility"
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [ "storage_facility:9095" ]
        labels:
          microservice: storage_facility

