#%RAML 1.0 ResourceType
#
# see:
#  https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#resource-types-and-traits

usage: >
  This resource type should be used as a child of items
  within a collection.  It exposes the ability to alter
  an entity's status by providing its id in the
  `uriParameters` and what version in the body.
  
  Whether or not a specific semantic action is possibly
  allowed is determined by the relevant service.  This is
  expressed by being present within the `_links` collection
  of the **ResourceObject**.

uriParameters:
  <<itemIdParameter>>: <<itemIdType>>

post:
  displayName: Attempt to <<resourcePathName>> the <<resource>>.

  headers:
    X-Correlation-ID:
      description: >
        Each request **must** be accompanied by an identifier chosen
        by the invoker and must be a valid string representation of
        a UUID.  Furthermore, the UUID **must** be version 3 or above.

      type: UUID

  body:
    application/json:
      type: VersionOnly

  responses:
    200:
      body:
        application/json:
          type: <<resource>>

    400:
      body:
        application/problem+json:
          type: ProblemDetails

    404:
      body:
        application/problem+json:
          type: ProblemDetails

    409:
      body:
        application/problem+json:
          type: ProblemDetails

    500:
      body:
        application/problem+json:
          type: ProblemDetails

